### PR TITLE
Update source2bags entry point to work with new sourced ml

### PR DESCRIPTION
**Pull request by zurk**
PTAL https://github.com/src-d/ml/pull/171 first

`source2bags` produce the same output, so everything should work. 

Only features that require uast2quant transformer does not work now. 
Need to fix uast2quant first, in another PR.

### CODE REVIEW

**Comment by zurk** [comment]
Related to https://github.com/src-d/apollo/issues/18

**Comment by vmarkovtsev** [comment]
Waiting for ml PRs to be mrged before merging this.

**Comment by vmarkovtsev** [comment]
@zurk Please bump this to run Travis again

**Comment by zurk** [comment]
Fails for python 3.4 only. https://travis-ci.org/src-d/apollo/builds/334748929?utm_source=github_status&utm_medium=notification

 but I was before me (for example https://travis-ci.org/src-d/apollo/builds/327692405)
Do you want me to fix it?

**Comment by vmarkovtsev** [comment]
Yes please

**Comment by vmarkovtsev** [comment]
@zurk Can you please recreate this PR - I pushed to your remote and it automatically closed.

**Comment by zurk** [comment]
Sorry, did not have time to react.

**Pull request closed without merging**
